#!/usr/bin/env python3
"""mksamples.py — bake samples/*.raw into a single samples.h.

Usage:
    python tools/mksamples.py <sample_dir> <output.h>

Expects 8-bit SIGNED mono raw at 48kHz, one file per VOICE SLOT (not per mode
— NIBBLE-KO has no modes, just 12 flat slots matching the twelve DRUMS
gestures in drums.cpp's kGestureVoice table):

    voice00.raw .. voice11.raw

A slot with no file gets a silent stub, so a fresh clone still compiles and
that voice simply plays nothing until either a .raw is added here or the
WebUI is used to assign it a sample after flashing.

Ported from WorkshopBio/tools/mksamples.py (see that file for the emit()
dedup trick), with the mode x round-robin-variant grid collapsed to one flat
array per slot — NIBBLE-KO does not round-robin, each slot is one sound.

TODO(design session): whether/how a slot round-robins between several
uploaded samples is undecided — see drums.h's VoiceSource TODO. This script
and samples_default.h assume ONE sample per slot until that is designed.

Converting a wav with ffmpeg:
    ffmpeg -i kick.wav -ac 1 -ar 48000 -f s8 samples/voice00.raw

Flash budget: 2MB total. See samplestore.h (once written) for how much of
that a user-upload region reserves.
"""
import os
import sys

NUM_VOICES = 12          # must match kNumVoices in drums.h


def load_slot(sample_dir, i):
    path = os.path.join(sample_dir, f"voice{i:02d}.raw")
    if os.path.isfile(path):
        with open(path, "rb") as f:
            return f.read()
    return None


def emit_slot(i, data):
    name = f"voice{i:02d}"
    lines = [f"const uint32_t {name}_pcm_len = {len(data)};",
             f"const signed char {name}_pcm[] = {{"]
    for j in range(0, len(data), 16):
        chunk = data[j:j + 16]
        # Raw bytes are unsigned; reinterpret as signed two's complement.
        lines.append("    " + "".join(
            f"{b - 256 if b > 127 else b}," for b in chunk))
    lines.append("};")
    return lines


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    sample_dir, out_path = sys.argv[1], sys.argv[2]

    out = ["// Auto-generated by tools/mksamples.py. Do not edit by hand.",
           "#pragma once", "#include <stdint.h>", ""]
    total = 0
    have = []
    for i in range(NUM_VOICES):
        data = load_slot(sample_dir, i)
        if data is None:
            out += [f"const uint32_t voice{i:02d}_pcm_len = 0;",
                     f"const signed char voice{i:02d}_pcm[] = {{0}};", ""]
            continue
        have.append(i)
        total += len(data)
        print(f"  voice{i:02d}: {len(data)} bytes")
        out += emit_slot(i, data)
        out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {out_path}: {total} bytes of PCM across {len(have)} slot(s) "
          f"({total / 48000.0:.2f}s at 48kHz)")


if __name__ == "__main__":
    main()
