#!/usr/bin/env python3
"""mksamples.py — bake samples/*.raw into a single samples.h.

Usage:
    python tools/mksamples.py <sample_dir> <output.h>

Expects 8-bit SIGNED mono raw at 48kHz, named smpNN.raw and numbered from
zero:

    smp00.raw  smp01.raw  smp02.raw ...

A BANK, not a per-voice list. Sample NN is not "the sound of voice NN" — it
is entry NN of a library, and which voice plays it is a separate mapping
(kVoiceSample in samples_default.h, and eventually whatever the WebUI
stores). That indirection is the whole point: the browser will let any bank
entry be assigned to any of the twelve voice slots, so baking a
sample-per-slot would have to be undone the moment that lands.

Two consequences worth knowing:

  * The bank can be LARGER than twelve. Ship a library, map five of them.
  * The same entry can be used by several voices at no extra flash cost,
    because the mapping is indices rather than copies.

Ported from WorkshopBio/tools/mksamples.py.

Converting a wav by hand:
    ffmpeg -i kick.wav -ac 1 -ar 48000 -f s8 samples/smp00.raw

...though tools/importwav.py does that, plus trimming, levelling and dither.

Flash budget: 2MB total, of which the firmware currently uses ~5%. At 48kHz
8-bit mono a second of audio is 48KB, so a bank of short one-shots is cheap —
about 1.2MB is available before samplestore.h's user region starts.
"""
import os
import re
import sys

MAX_SAMPLES = 64          # must match kMaxSamples in samples_default.h


def load_bank(sample_dir):
    """Return [(index, bytes)] for every smpNN.raw present, in index order."""
    out = []
    if not os.path.isdir(sample_dir):
        return out
    for name in sorted(os.listdir(sample_dir)):
        m = re.fullmatch(r"smp(\d+)\.raw", name)
        if not m:
            continue
        idx = int(m.group(1))
        if idx >= MAX_SAMPLES:
            print(f"  {name}: index {idx} past the {MAX_SAMPLES} limit, skipped")
            continue
        with open(os.path.join(sample_dir, name), "rb") as f:
            out.append((idx, f.read()))
    return out


def emit(entries):
    """One flat array plus per-entry offsets and sizes.

    Concatenated rather than one array each, because a hundred small arrays
    is a hundred symbols for the linker and an awkward table to index. Offsets
    into one blob are simpler and let an empty slot be a zero-length span
    rather than a special case.
    """
    blob = bytearray()
    offs = [0] * MAX_SAMPLES
    sizes = [0] * MAX_SAMPLES
    for idx, data in entries:
        offs[idx] = len(blob)
        sizes[idx] = len(data)
        blob += data

    lines = [f"const uint32_t kSampleBankLen = {len(blob)};",
             f"const uint32_t kSampleOff[{MAX_SAMPLES}] = {{"
             + ", ".join(str(o) for o in offs) + "};",
             f"const uint32_t kSampleSize[{MAX_SAMPLES}] = {{"
             + ", ".join(str(s) for s in sizes) + "};",
             "const signed char kSampleBank[] = {"]
    if not blob:
        # A zero-length array is not valid C++; one silent byte keeps the
        # symbol real without anything being able to play it (size 0 above).
        lines.append("    0,")
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        # Raw bytes are unsigned; reinterpret as signed two's complement.
        lines.append("    " + "".join(
            f"{b - 256 if b > 127 else b}," for b in chunk))
    lines.append("};")
    return lines, len(blob)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    sample_dir, out_path = sys.argv[1], sys.argv[2]

    entries = load_bank(sample_dir)
    for idx, data in entries:
        print(f"  smp{idx:02d}: {len(data):6d} bytes ({len(data)/48.0:5.0f} ms)")

    lines, total = emit(entries)
    out = ["// Auto-generated by tools/mksamples.py. Do not edit by hand.",
           "#pragma once", "#include <stdint.h>", ""] + lines

    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {out_path}: {total} bytes across {len(entries)} sample(s) "
          f"({total / 48000.0:.2f}s at 48kHz)")


if __name__ == "__main__":
    main()
